"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import type { GeneratedCourse } from "@/app/services/ai/types";
import type { ProductPublication } from "@/app/services/marketplace/marketTypes";
import { CoursePlayer } from "@/app/create/builder/components/CoursePlayer";

const FONT: string = '"Inter", system-ui, -apple-system, "Segoe UI", Roboto, sans-serif';

export function LearnClient() {
  const params = useParams<{ id: string }>();
  const router = useRouter();
  const [denied, setDenied] = useState(false);
  const [product, setProduct] = useState<ProductPublication | null>(null);
  const [course, setCourse] = useState<GeneratedCourse | null>(null);

  useEffect(() => {
    // 1. Fetch product from API (server-side)
    fetch(`/api/products/${encodeURIComponent(params.id)}`)
      .then((r) => r.json())
      .then(async (data) => {
        if (!data.ok || !data.product) {
          setDenied(true);
          return;
        }
        const pub = data.product as ProductPublication;
        if (pub.format !== "course") {
          setDenied(true);
          return;
        }
        setProduct(pub);
        // 2. Check access server-side (the client NEVER decides)
        const accessRes = await fetch(`/api/access?productId=${encodeURIComponent(pub.id)}`);
        const accessData = await accessRes.json();
        if (!accessData.ok || !accessData.hasAccess) {
          setDenied(true);
          return;
        }
        // 3. Load course content from localStorage (generated by creator)
        try {
          const raw = window.localStorage.getItem("crow_last_course");
          if (raw) {
            setCourse(JSON.parse(raw) as GeneratedCourse);
          } else {
            setDenied(true);
          }
        } catch {
          setDenied(true);
        }
      })
      .catch(() => setDenied(true));
  }, [params.id]);

  if (denied) {
    return (
      <main style={{ minHeight: "100vh", background: "#050505", color: "#fff", fontFamily: FONT, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: "40px" }}>
        <h1 style={{ fontSize: "24px" }}>Acceso denegado (403)</h1>
        <p style={{ color: "#888" }}>Necesitás haber comprado este curso para acceder.</p>
        <button onClick={() => router.push("/marketplace")} style={{ marginTop: "16px", padding: "12px 24px", borderRadius: "10px", border: "none", background: "#7c3aed", color: "#fff", fontWeight: "bold", cursor: "pointer" }}>
          Ir al Marketplace
        </button>
      </main>
    );
  }

  if (!course || !product) {
    return (
      <main style={{ minHeight: "100vh", background: "#050505", color: "#fff", fontFamily: FONT, display: "flex", alignItems: "center", justifyContent: "center" }}>
        <div style={{ color: "#888" }}>Cargando tu curso...</div>
      </main>
    );
  }

  return (
    <main style={{ minHeight: "100vh", background: "#050505", color: "#fff", fontFamily: FONT }}>
      <div style={{ padding: "12px 4%", borderBottom: "1px solid rgba(255,255,255,0.08)" }}>
        <Link href="/my-products" style={{ color: "#aaa", textDecoration: "none", fontSize: "13px" }}>← Mis productos</Link>
      </div>
      <CoursePlayer course={course} progressKey={`crow_learn_progress_${product.id}`} />
    </main>
  );
}
